---
title: "Skills Quiz - Confidence and Prediction Intervals"
author: "Brigham Eaquinto"
date: "10/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("alr4")
library(alr4) 
library(tidyverse)
# ?BGSall
# View(BGSall)
colnames(BGSall)
```

```{r}
mylm <- lm(HT18~HT2, data = BGSall)
summary(mylm)

b0_residual_std_error <- summary(mylm)$coefficients[1,2]
b1_residual_std_error <- summary(mylm)$coefficients[2,2]

df <- summary(mylm)$df[2]

b0 <- mylm$coef[1]
b1 <- mylm$coef[2]

predict(mylm, data.frame(HT2 = 12), interval = "prediction") 
predict(mylm, data.frame(HT2 = 12), interval = "confidence") 


t_test_b0 <- (b0 - 2)/ b1_residual_std_error
t_test_b0
t_test_b1 <- (b1 - 2)/ b1_residual_std_error
t_test_b1


pt(-abs(t_test_b0), df)
pt(-abs(t_test_b1), df)

ggplot(BGSall, aes(HT2, HT18))+
  geom_smooth(method = "lm", formula = y~x, se = TRUE, color = "green")+
  geom_point(color = "orange")+
  labs(title = "Height from Age 2 to Age 18", 
       subtitle = "BGSall data from library(alr3)")+
  theme_bw()

```


$$
  \underbrace{Y_i}_\text{Height 18} = \beta_0 + \beta_1 \underbrace{X_i}_\text{Height 2} + \epsilon_i \quad \text{where} \ \epsilon_i \sim N(0, \sigma^2)
$$



```{r}

mylm <- lm(Scale~Length, data = wblake)
summary(mylm)

mylm.sqrt <- lm(sqrt(Scale)~Length, data = wblake)
summary(mylm.sqrt)

#coef just grabs things from the lm summary

b <- coef(mylm)
b.sqrt <- coef(mylm.sqrt)

ggplot(wblake, aes(Length, Scale))+
  geom_point()+
  stat_function(fun = function(x) b[1] + b[2]* x, color = "red")+
  stat_function(fun = function(x) (b.sqrt[1] + b.sqrt[2]* x)^2, color = "pink")

predict(mylm.sqrt, data.frame(Length = 250), interval = "prediction")^2

```

